apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    # Watch this image in the container registry
    argocd-image-updater.argoproj.io/image-list: myapp=mydockerhubuser/myapp
    # Always pick the newest image tag
    argocd-image-updater.argoproj.io/myapp.update-strategy: newest
    # Write back updated image tag to Git
    argocd-image-updater.argoproj.io/write-back-method: git
    # Helm chart value to update
    argocd-image-updater.argoproj.io/helm.image-tag: image.tag
spec:
  project: default

  source:
    repoURL: https://github.com/hemanthmallam123/Practice.git
    targetRevision: main
    path: myapp
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true



